<?
$PERM["sluzhba-podderzhki"]["5"]="R";
$PERM["settings-profile"]["5"]="R";
$PERM["documents"]["5"]="R";
$PERM["batteries"]["5"]="R";
$PERM["documents"]["3"]="R";
$PERM["batteries"]["3"]="R";
$PERM["obozrevatel-obektov"]["3"]="R";
$PERM["clients"]["5"]="R";
$PERM["calendar"]["5"]="R";
$PERM["/"]["3"]="R";
$PERM["/"]["*"]="D";
?>