<?
$aMenuLinks = Array(
	Array(
		"Список батарей", 
		"/batteries/", 
		Array(), 
		Array("src"=>"/local/templates/vertrieb/img/sprite.svg#sidebar-menu-battery-icon"),
		"" 
	),
    Array(
        "Клиенты",
        "/clients/",
        Array(),
        Array("src"=>"/local/templates/vertrieb/img/sprite.svg#sidebar-menu-clients-icon"),
        ""
    ),
    Array(
        "Календарь",
        "/calendar/",
        Array(),
        Array("src"=>"/local/templates/vertrieb/img/sprite.svg#sidebar-menu-calendar-icon"),
        ""
    ),
	Array(
		"Документация", 
		"/documents/", 
		Array(), 
		Array("src"=>"/local/templates/vertrieb/img/sprite.svg#sidebar-menu-docs-icon"),
		"" 
	)
);
?>